name: "Sonar Quality Gate"
description: "Verify if the PR or Branch has the quality gate passing"
inputs:
  sonar_login:
    description: "The login or authentication token of a SonarQube user with Execute Analysis permission on the project."
    required: true
  sonar_project_settings:
    description: "The Sonar properties file where the project information's can be found"
    required: false
    default: "sonar-project.properties"
  sonar_working_directory:
    description: "The working directory for an analysis triggered with the SonarScanner"
    required: false
    default: ".scannerwork"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.sonar_login }}
    - ${{ inputs.sonar_project_settings }}
    - ${{ inputs.sonar_working_directory }}
  pre-entrypoint: '/scripts/pre-entrypoint.sh'
  entrypoint: '/scripts/entrypoint.sh'
  post-entrypoint: '/scripts/post-entrypoint.sh'