name: 'CodePush Validation Action'
description: 'GitHub Action that validates if the CodePush could be executed or not'
author: 'Victor Hugo dos Santos'
inputs:
  base_branch:
    description: 'The base branch to compare against'
    required: true
    default: 'main'
  package_json_path:
    description: 'The path to the package.json file'
    required: false
    default: 'package.json'
  android_path:
    description: 'The path to the Android project'
    required: false
    default: 'android/'
  ios_path:
    description: 'The path to the iOS project'
    required: true
    default: 'ios/'
  yarn_lock_path:
    description: 'The path to the yarn.lock file'
    required: false
    default: 'yarn.lock'
outputs:
  codepush_deployment: 
    description: 'The codepush deployment'
branding:
  icon: upload-cloud
  color: purple
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.base_branch }}
    - ${{ inputs.package_json_path }}
    - ${{ inputs.android_path }}
    - ${{ inputs.ios_path }}
    - ${{ inputs.yarn_lock_path }}
