on: 
  workflow_call:
    inputs:
      message:
        required: true
        type: string
        default: 'Hello World'

jobs:
  show-message: 
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.message }}

