name: Bump Version

on:
  workflow_dispatch:
    inputs:
      hotfix:
        default: "false"
        description: "Bump version to hotfix"
        required: true
      version:
        description: The version to bump to (e.g. v1.0.0)
        required: true
      project:
        default: mobile-platform
        description: The project to bump the version of (e.g. mobile-platform, tv-platform, web-platform)
        required: true

jobs:
  bump-mobile-hotfix-version:
    runs-on: ubuntu-latest
    if: github.event.inputs.project == 'mobile-platform' && github.event_name == 'workflow_dispatch' && github.event.inputs.hotfix == 'true'
    strategy:
      matrix:
        base-branch: [main, develop]
      max-parallel: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump GitHub Secret version
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: APP_VERSION
          value: ${{ github.event.inputs.version }}
          repository: vhsantos26/github-actions-tests
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Bump Package version
        run: yarn --new-version version ${{ github.event.inputs.version }} --no-git-tag-version --no-commit-hooks

      - name: Bump Sonar Project properties version
        run: sed -i -e 's/^sonar.projectVersion.*$/sonar.projectVersion=${{ github.event.inputs.version }}/' sonar-project.properties

      - name: Bump Build Gradle version
        run: sed -i -e "s/app_version=\".*\"/app_version=\"${{ github.event.inputs.version }}\"/" android/app/build.gradle

      - name: Create Hotfix Pull Request (${{ matrix.base-branch }})
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Hotfix ${{ github.event.inputs.version }}
          branch: hotfix-${{ github.event.inputs.version }}
          delete-branch: true
          base: ${{ matrix.base-branch }}
          title: Hotfix ${{ github.event.inputs.version }}
          labels: |
            ${{ matrix.base-branch }}
            hotfix-${{ github.event.inputs.version }}
          body: |
            ## Summary: 
            - Version: ${{ github.event.inputs.version }}

  bump-mobile-release-version:
    runs-on: ubuntu-latest
    if: github.event.inputs.project == 'mobile-platform' && github.event_name == 'workflow_dispatch' && github.event.inputs.hotfix == 'false'
    strategy:
      matrix:
        base-branch: [develop, main]
      max-parallel: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump GitHub Secret version
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: APP_VERSION
          value: ${{ github.event.inputs.version }}
          repository: vhsantos26/github-actions-tests
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Bump Package version
        run: yarn --new-version version ${{ github.event.inputs.version }} --no-git-tag-version --no-commit-hooks

      - name: Bump Sonar Project properties version
        run: sed -i -e 's/^sonar.projectVersion.*$/sonar.projectVersion=${{ github.event.inputs.version }}/' sonar-project.properties

      - name: Bump Build Gradle version
        run: sed -i -e "s/app_version=\".*\"/app_version=\"${{ github.event.inputs.version }}\"/" android/app/build.gradle

      - name: Create Release Pull Request (${{ matrix.base-branch }})
        if: github.event.inputs.hotfix == 'false'
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Release ${{ github.event.inputs.version }}
          branch: rc-${{ github.event.inputs.version }}
          delete-branch: true
          base: ${{ matrix.base-branch }}
          title: Release ${{ github.event.inputs.version }}
          labels: |
            ${{ matrix.base-branch }}
            rc-${{ github.event.inputs.version }}
          body: |
            ## Summary: 
            - Version: ${{ github.event.inputs.version }}
