name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to bump to (e.g. v1.0.0)
        required: true
      project:
        default: mobile-platform
        description: The project to bump the version of (e.g. mobile-platform, tv-platform, web-platform)
        required: true

jobs:
  bump-mobile-version:
    # runs-on: [self-hosted, linux, ump-mobile]
    runs-on: ubuntu-latest
    if: github.event.inputs.project == 'mobile-platform' && github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump GitHub Secret version
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: APP_VERSION
          value: ${{ github.event.inputs.version }}
          repository: vhsantos26/github-actions-tests
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Bump Package version
        env:
          APP_VERSION: ${{ secrets.APP_VERSION }}
        run: yarn --new-version version ${{ env.APP_VERSION }} --no-git-tag-version --no-commit-hooks

      - name: Bump Sonar Project properties version
        env:
          APP_VERSION: ${{ secrets.APP_VERSION }}
        run: sed -i -e 's/^sonar.projectVersion.*$/sonar.projectVersion=${{ env.APP_VERSION }}/' sonar-project.properties

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.10.1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Bump version to ${{ github.event.inputs.version }}
          branch: bump-version/${{ github.event.inputs.version }}
          delete-branch: true
          base: main
          title: Bump version to ${{ github.event.inputs.version }}
          body: |
            ## New version: ${{ github.event.inputs.version }}
          milestone: v${{ github.event.inputs.version }}
