name: continuous integration

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore: 
      - .github/workflows/tests.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        
  danger-pr-check:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        
  linters:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      
  static-analysis:
    runs-on: ubuntu-latest
    needs: 
      - unit-tests
      - danger-pr-check
      - linters
    steps:
      - uses: actions/checkout@v2
          
  query-map-sync:
    runs-on: ubuntu-latest
    needs: static-analysis
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
          
  push-to-staging:
    runs-on: ubuntu-latest
    needs: query-map-sync
    strategy:
      matrix:
        clients: [aje, aja, ajc, ajm]
    environment: 
      name: Staging
      url: ${{ steps.push-to-vip.outputs.url_output }}
    steps:
      - uses: actions/checkout@v2

      - name: Push to VIP
        id: push_to_vip
        run: |
          echo "::set-output name=url_output::https://staging.${{ matrix.clients }}.aj-harbinger.com"
          
  push-to-production:
    runs-on: ubuntu-latest
    needs: query-map-sync
    if: always()
    outputs:
      status: ${{ job.status }}
    strategy:
      matrix:
        clients: [aje, aja, ajc, ajm]
    environment:
      name: Production
      url: ${{ steps.push_to_vip.outputs.url_output }}
    steps:
      - uses: actions/checkout@v2
        
      - name: Push to VIP
        id: push_to_vip
        env:
          URL: |
            ${{ 
              ( matrix.clients == 'aje' && 'https://aljazeera.com' )
              || ( matrix.clients == 'aja' && 'https://aljazeera.net')
              || ( matrix.clients == 'ajc' && 'https://chinese.aljazeera.net' )
              || ( matrix.clients == 'ajm' && 'https://mubasher.aljazeera.net' )
            }}
        run: |
          echo "::set-output name=url_output::$URL"
