name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: |
      Build and Test
    runs-on: ubuntu-latest
    steps:
      - run: echo 'build'
        if: ${{ env.IS_RELEASE == 'true' }}

  build-ios:
    name: |
      Build iOS
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - run: echo 'ios'

  build-android:
    name: |
      Build Android
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - run: echo 'android'

  functional-tests:
    name: |
      Functional Tests
    runs-on: ubuntu-latest
    needs: [build-ios, build-android]
    strategy:
      matrix:
        os: [ios, android]
    steps:
      - run: echo ${{ matrix.os }}
      
  deploy-to-firebase:
    name: |
      Deploy to Firebase
    runs-on: ubuntu-latest
    needs: functional-tests
    strategy:
      matrix:
        os: [ios, android]
    steps:
      - run: echo ${{ matrix.os }}
      
      
  deploy-to-amazon-appstore:
    name: |
      Deploy to Amazon AppStore
    runs-on: ubuntu-latest
    needs: deploy-to-firebase
    environment: 
      name: release
    if: contains(github.ref, 'develop')
    steps:
      - run: echo 'deploy to amazon appstore'

  
      
