on: [push, pull_request]

jobs:
  test:
    name: |
      Test
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(secrets.GOOGLE_APPLICATION_CREDENTIALS) }}' > al-jazeera-mobile-platform.json
      
      
      - name: Setup Node Version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ secrets.NODE_VERSION }}
          check-latest: true
      
      - run: cat al-jazeera-mobile-platform.json
      
      - env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ github.workspace }}/al-jazeera-mobile-platform.json"
        if: false
        run: echo ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        
      - name: Post deployment
        if: always()
        run: rm -rf "${{ github.workspace }}/al-jazeera-mobile-platform.json"
        
      - run: ls -la .
