name: Continuous Integration

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
        continue-on-error: true
        
      - run: echo '${{ toJSON(github) }}'
      
      - run: ls -la .
