on: [push, pull_request]

jobs:
  test:
    name: |
      Test
    runs-on: ubuntu-latest
    steps:
    
      - uses: jsdaniell/create-json@v1.2.1
        with:
          name: "al-jazeera-mobile-platform.json"
          json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    
      - run: echo "GOOGLE_APPLICATION_CREDENTIALS=$(${{ github.workspace }}/al-jazeera-mobile-platform.json)" >> $GITHUB_ENV
      
      - run: echo ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
