on: [push, pull_request]

jobs:
  test:
    name: |
      Test
    runs-on: ubuntu-latest
    steps:
      - name: Save JSON context to a file
        run: echo '${{ toJson(github) }}' > github_context.json

      - name: Upload JSON context as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-context
          path: github_context.json
          
      - name: Install jq
        run: sudo apt-get install -y jq
        
      - name: Get jobs context as JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jobs_context=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs")
          echo "$jobs_context" > jobs_context.json
          
      - name: Upload jobs context as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: jobs-context
          path: jobs_context.json

  deploy-google-playstore:
    name: Deploy to Google PlayStore
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform: ["mobile", "tv"]
    steps:
      - if: matrix.type == 'mobile'
        uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
