on: [push, pull_request]

jobs:
  test:
    name: |
      Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(secrets.GOOGLE_APPLICATION_CREDENTIALS) }}' > al-jazeera-mobile-platform.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(${{.github.workspace }}/al-jazeera-mobile-platform.json) >> $GITHUB_ENV
      
      - run: echo ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
