on: [push, pull_request]

jobs:
  test:
    name: |
      Test
    runs-on: ubuntu-latest
    steps:
      - name: Save JSON context to a file
        run: echo '${{ toJson(github) }}' > github_context.json

      - name: Upload JSON context as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-context
          path: github_context.json
          
      - name: Save job context to a file
        run: echo '${{ toJson(jobs) }}' > job_context.json
        
      - name: Upload JSON context as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: job-context
          path: job_context.json
