on: [push, pull_request]

jobs:
  test:
    name: |
      Test
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(secrets.GOOGLE_APPLICATION_CREDENTIALS) }}' > al-jazeera-mobile-platform.json
      
      - run: vi al-jazeera-mobile-platform.json
