name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  IS_RELEASE: ${{ (contains(github.ref, 'develop') || startsWith(github.head_ref, 'hotfix-')) && 'true' || 'false' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: env.IS_RELEASE == 'true'
    steps:
      - run: echo 'build'

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo 'test'

      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" >> ./ci-github-context.json

      - name: Upload GitHub Context
        uses: actions/upload-artifact@v2
        with:
          name: ci-github-context
          path: ./ci-github-context.json
          retention-days: 5
