on: push

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      retention-days: ${{ contains(github.ref, 'master') && 5 || 90 }}
      
    steps:
      - run: echo '${{ toJSON(github) }}' >> github-context.json

      - uses: actions/upload-artifact@v3
        with:
          path: github-context.json
          retention-days: ${{ env.retention-days }}
