on: [push, pull_request]

jobs:
  test:
    name: |
      Test
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(secrets.GOOGLE_APPLICATION_CREDENTIALS) }}' > al-jazeera-mobile-platform.json
      
      - env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ github.workspace }}/al-jazeera-mobile-platform.json"
        run: echo ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        
      - name: Post deployment
        run: rm -rf "${{ github.workspace }}/al-jazeera-mobile-platform.json"
