on: push

env:
  is-release: ${{ contains(github.ref, 'dev') && (startsWith(github.actor, 'vhsantos26') || startsWith(github.head_ref, 'hotfix-')) }}

jobs:
  test:
    name: |
      Deploy to GitHub Release
    runs-on: ubuntu-latest
    env:
      retention-days: ${{ contains(github.ref, 'dev') && 5 || 90 }}
      
    steps:
      - run: echo '${{ toJSON(github) }}' >> github-context.json

      - uses: actions/upload-artifact@v3
        if: env.is-release == 'true'
        with:
          path: github-context.json
          retention-days: ${{ env.retention-days }} 
  deploy:
    runs-on: ubuntu-latest
    needs: test
    environment: testflight
    steps:
      - run: echo "Deploying"
      
