on: 
  pull_request: 
    types: 
      - closed

jobs:
  clean-cache:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    name: Clean Cache
    steps:
      - name: Clean Cache
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Starting cache cleanup process...');

            const { actions_caches } = await github.rest.actions.listRepoCaches({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            console.log('Fetched caches:', actions_caches);

            const cacheIds = actions_caches.filter(cache => cache.ref === github.ref).map(cache => cache.id);
            const uniqueCacheIds = [...new Set(cacheIds)];

            console.log('Cache IDs to delete:', uniqueCacheIds);

            for (const id of uniqueCacheIds) {
              console.log(`Deleting cache with ID: ${id}`);
              await github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: id,
              });
              console.log(`Deleted cache with ID: ${id}`);
            }

            console.log('Cache cleanup process completed.');
