on:
  workflow_dispatch: 

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          server_port: 465
          secure: true
          subject: "[GitHub] Your Package Outdated report for this week"
          to: santosv@aljazeera.net
          from: not-reply@mailer.aljazeera.net
          body: GitHub version alert digest
