name: End-to-end Execution

on:
  workflow_run:
    workflows: [Continuous Integration/Delivery]
    types: [completed]

jobs:
  end-to-end-execution:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: End-to-end Execution 
    strategy:
      matrix:
        platform: [ios, android]
    steps:
      - run: echo "End-to-end Execution (${{ matrix.platform }})"
      
      - name: Create Context Json file
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT >> github.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./github.json
          name: e2e-workflow
