name: End-to-end Workflow

on:
  repository_dispatch:
    types: [start-end-to-end-workflow]

jobs:
  end-to-end-execution:
    runs-on: ubuntu-latest
    name: ${{ github.event.client_payload.device-capabilities.platform-name }} execution
    steps:
      - name: External workflow step
        run: echo "This is an external workflow."

      - name: Replace Workflow Name
        run: echo "WORKFLOW_NAME=${{ github.event.client_payload.branch-name }} - ${{ github.event.client_payload.device-capabilities.platform-name }} End-to-end Workflow" >> $GITHUB_ENV

      - name: Run Functional Tests
        env:
          APP_FILE_ID: ${{ github.event.client_payload.sauce-labs-options.file-id }}
          SAUCE_USERNAME: ${{ github.event.client_payload.sauce-labs-options.username }}
          SAUCE_ACCESS_KEY: ${{ github.event.client_payload.sauce-labs-options.access-key }}
          APPIUM_VERSION: ${{ github.event.client_payload.sauce-labs-options.access-key }}
          PLATFORM_NAME: ${{ github.event.client_payload.device-capabilities.platform-name }}
          PLATFORM_VERSION: ${{ github.event.client_payload.device-capabilities.platform-version }}
          DEVICE_NAME: ${{ github.event.client_payload.device-capabilities.device-name }}
          PHONEONLY: ${{ github.event.client_payload.device-capabilities.phoneonly }}
          BRANCH_NAME: ${{ github.event.client_payload.branch-name }}
        run: echo "running test"
        id: remote-e2e
