name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  NODE_VERSION: 20

jobs:
  build-mobile:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    name: Build & Test Mobile
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true
          cache: 'yarn'
