name: Publish GitHub Release

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      duration:
        type: number
        description: "Load Test Duration (in Minutes)"
        options:
          - '1'
          - '3'
          - '10'
        required: true
    

jobs:
  test:
    runs-on: ${{ vars.LINUX_RUNNER }}
    steps:
      - run: |
          echo ${{ inputs.duration }}
          test=${{ inputs.duration }}
          echo test * 5
