on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
env:
  is-release: ${{ github.base_ref == 'develop' && (startsWith(github.head_ref, 'rc-') || startsWith(github.head_ref, 'hotfix-')) || contains(github.ref, 'develop') }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build"

      - if: env.is-release == 'true'
        run: echo "It's a release"

  deploy-sauce-labs:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        platform-name: [android, ios]
    steps:
      - run: echo "Deploy to Sauce Labs"

      - if: ${{ matrix.platform-name == 'ios' }}
        id: ios-sauce-labs-upload
        run: |
          echo "file-id='86757a2d-f222-48a5-b4c9-422d4811ef6a'" >> $GITHUB_OUTPUT
          echo "device-name='iPhone 12 Simulator'" >> $GITHUB_OUTPUT
          echo "platform-version='14.5'" >> $GITHUB_OUTPUT

      - if: ${{ matrix.platform-name == 'android' }}
        id: android-sauce-labs-upload
        run: |
          echo "file-id='bad03d3a-ef5b-40fe-b200-139872a2606a'" >> $GITHUB_OUTPUT
          echo "device-name='Samsung Galaxy S20 Ultra GoogleAPI Emulator'" >> $GITHUB_OUTPUT
          echo "platform-version='11.0'" >> $GITHUB_OUTPUT

      - run: echo "${{ toJSON(github.event) }}" >> github-event.json

      - name: Upload GitHub Event Detail
        uses: actions/upload-artifact@v2
        with:
          name: github-event-detail
          path: github-event.json

      - name: Dispatch end-to-end workflow
        uses: peter-evans/repository-dispatch@v2
        env:
          FILE-ID: ${{ matrix.platform-name == 'ios' && steps.ios-sauce-labs-upload.outputs.file-id || steps.android-sauce-labs-upload.outputs.file-id }}
          PLATFORM-VERSION: ${{ matrix.platform-name == 'ios' && steps.ios-sauce-labs-upload.outputs.platform-version || steps.android-sauce-labs-upload.outputs.platform-version }}
          DEVICE-NAME: ${{ matrix.platform-name == 'ios' && steps.ios-sauce-labs-upload.outputs.device-name || steps.android-sauce-labs-upload.outputs.device-name }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: vhsantos26/github-actions-tests
          event-type: start-end-to-end-workflow
          client-payload: '{"sauce-labs-options":{"username":"${{ secrets.SAUCE_LABS_USERNAME }}","access-key":"${{ secrets.SAUCE_LABS_ACCESS_KEY }}","file-id":"${{ env.FILE-ID }}","appium-version":"${{ vars.APPIUM_VERSION }}"},"device-capabilities":{"platform-name":"${{ matrix.platform-name }}","platform-version":"${{ env.PLATFORM-VERSION }}","device-name":"${{ env.DEVICE-NAME }}","phoneonly":true},"branch-name":"${{ github.ref_name }}"}'
