name: continuous integration

on:
  workflow_dispatch:
#   schedule:
#     - cron: "*/6 * * * *"

env:
  ENVRIONMENT: |
    ${{ 
      (1 == 1 && 'prod')
      || ( 1 == 0 && 'stage')
    }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        clients: [aje, aja, ajb, ajc, ajm]
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" > github_context.json

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: github_context.json
          
      - name: Context Conditional
        env:
          url: |
            ${{ 
              (matrix.clients == 'aje' && 'aljazeera.com' )
              || ( matrix.clients == 'aja' && 'aljazeera.net')
              || ( matrix.clients == 'ajb' && 'balkans.aljazeera.net' )
              || ( matrix.clients == 'ajc' && 'chinese.aljazeera.net' )
              || ( matrix.clients == 'ajm' && 'mubasher.aljazeera.net' )
            }}
        run: echo $url
        
      - name: Check env
        env:
          TEST: $env.ENVRIONMENT
        run: echo $TEST
