name: Main Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
      
env:
  RELEASE: ${{ (contains(github.ref, 'main') || startsWith(github.head_ref, 'hotfix-')) && true || false }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.RELEASE }}
      
      - run: echo "here"
        if: env.RELEASE

      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" >> ./github-context.json

      - name: Upload GitHub Context
        uses: actions/upload-artifact@v2
        with:
          name: github-context
          path: ./github-context.json
          retention-days: 5
