# This is a basic workflow to help you get started with Actions

name: CI

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" > github_contect.json

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: github_contect.json
          path: .
