name: Main Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build"

  deploy-sauce-labs:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        platform-name: [android, ios]
    steps:
      - run: echo "Deploy to Sauce Labs"

      - if: ${{ matrix.platform-name == 'ios' }}
        id: ios-sauce-labs-upload
        run: |
          echo "file-id='86757a2d-f222-48a5-b4c9-422d4811ef6a'" >> $GITHUB_OUTPUT
          echo "device-name='iPhone 12 Simulator'" >> $GITHUB_OUTPUT
          echo "platform-version='14.5'" >> $GITHUB_OUTPUT

      - if: ${{ matrix.platform-name == 'android' }}
        id: android-sauce-labs-upload
        run: |
          echo "file-id='bad03d3a-ef5b-40fe-b200-139872a2606a'" >> $GITHUB_OUTPUT
          echo "device-name='Samsung Galaxy S20 Ultra GoogleAPI Emulator'" >> $GITHUB_OUTPUT
          echo "platform-version='11.0'" >> $GITHUB_OUTPUT

      - name: Dispatch end-to-ed workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: vhsantos26/github-actions-tests
          event-type: start-end-to-end-workflow
          client-payload: >
            '{
              "sauce-labs-options": {
                "username": "${{ secrets.SAUCE_LABS_USERNAME }}",
                "access-key": "${{ secrets.SAUCE_LABS_ACCESS_KEY }}",
                "file-id": "${{ fromJson(steps[format('{0}-sauce-labs-upload.outputs', matrix.platform-name)].outputs)['file-id'] }}",
                "appium-version": "${{ vars.APPIUM_VERSION }}",
              },
              "device-capabilities": {
                "platform-name": "${{ matrix.platform-name }}",
                "platform-version": "${{ fromJson(steps[format('{0}-sauce-labs-upload.outputs', matrix.platform-name)].outputs)['platform-version'] }}",
                "device-name": "${{ fromJson(steps[format('{0}-sauce-labs-upload.outputs', matrix.platform-name)].outputs)['device-name'] }}",
                "phoneonly": true
              },
              "branch-name": "${{ github.ref_name }}"
            }'
