name: continuous integration

on:
  workflow_dispatch:
#   schedule:
#     - cron: "*/6 * * * *"

env:
  ENVRIONMENT: |
    ${{ 
      (1 == 1 && 'prod')
      || ( 1 == 0 && 'stage')
    }}

jobs:
  job1:
    if: 1 == 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - run: echo "First Job has the condition 1 == 1 to run"
    
  job2:
    if: 2 == 1
    runs-on: ubuntu=latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "Second Job doesn't have any rules to be executed"
        
  github-context:
    if: needs.job1.result == success || needs.job2.result == success
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" > github_context.json

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: github_context.json
