name: Main Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build"

  trigger-end-to-end-workflow:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Unit Test"

      - name: Dispatch end-to-ed workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: vhsantos26/github-actions-tests
          event-type: start-end-to-end-workflow
