on: 
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  share-context:
    uses: ./.github/workflows/share-context.yml
    with:
      file-name: pr-transition
        
