on: 
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  pr_transition:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/workflows/share-context@master
        with:
          file-name: pr-transition
        
