on: 
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  share-context:
    uses: ./.github/workflows/upload-context.yml
    with:
      file-name: pr-transition

  label-draft-pr:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == true
    steps:
      - name: Label PR as Draft
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['draft']
            })
