name: Publish GitHub Release

on:
  push:
    branches:
      - develop
      
permissions:
  contents: write
  
jobs:
  publish-github-release:
    runs-on: ${{ vars.LINUX_RUNNER }}
    steps:
      - uses: actions/checkout@v3

      - run: echo "version=2.10.0" >> $GITHUB_OUTPUT
        id: get_project_version

      - uses: ncipollo/release-action@v1.12.0
        if: false
        env:
          TAG: ${{ steps.get_project_version.outputs.version }}
        with:
          tag: v${{ env.TAG }}
          token: ${{ secrets.ACCESS_TOKEN }}
          generateReleaseNotes: true
          allowUpdates: true

      - uses: softprops/action-gh-release@v1
        if: true
        env: 
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TAG: ${{ steps.get_project_version.outputs.version }}
        with: 
          tag_name: v${{ env.TAG }}
          generate_release_notes: true
          
          
