on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish-github-release:
    runs-on: ${{ vars.LINUX_RUNNER }}
    if: true
    steps:
      - uses: actions/checkout@v3

      - run: echo "version=2.13.0" >> $GITHUB_OUTPUT
        id: get_project_version

      - uses: ncipollo/release-action@v1.12.0
        env:
          TAG: ${{ steps.get_project_version.outputs.version }}
        with:
          name: Mobile ${{ env.TAG }}
          tag: v${{ env.TAG }}
          token: ${{ secrets.ACCESS_TOKEN }}
          generateReleaseNotes: true
          allowUpdates: true
          skipIfReleaseExists: true
