name: Publish GitHub Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  publish-github-release:
    runs-on: ${{ vars.LINUX_RUNNER }}
    steps:
      - uses: actions/checkout@v3

      - run: echo "version=$(cat sonar-project.properties | grep sonar.projectVersion | cut -d '=' -f 2-)" >> $GITHUB_OUTPUT
        id: get_project_version

      - uses: softprops/action-gh-release@v1
        env:
          TAG: ${{ steps.get_project_version.outputs.version }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: v${{ env.TAG }}
          generate_release_notes: true
