name: Publish GitHub Release

on:
  push:
    branches:
      - main

jobs:
  publish-github-release:
    runs-on: ${{ vars.LINUX_RUNNER }}
    steps:
      - uses: actions/checkout@v3

      - run: echo "version=$(cat sonar-project.properties | grep sonar.projectVersion | cut -d '=' -f 2-)" >> $GITHUB_OUTPUT
        id: get_project_version

      - uses: ncipollo/release-action@v1.12.0
        env:
          TAG: ${{ steps.get_project_version.outputs.version }}
        with:
          tag: v${{ env.TAG }}
          token: ${{ secrets.ACCESS_TOKEN }}
          generateReleaseNotes: true
