on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
#   publish-github-release:
#     runs-on: ${{ vars.LINUX_RUNNER }}
#     if: true
#     steps:
#       - uses: actions/checkout@v3

#       - run: echo "version=2.13.0" >> $GITHUB_OUTPUT
#         id: get_project_version

#       - uses: ncipollo/release-action@v1.12.0
#         env:
#           TAG: ${{ steps.get_project_version.outputs.version }}
#         with:
#           name: Mobile ${{ env.TAG }}
#           tag: v${{ env.TAG }}
#           token: ${{ secrets.ACCESS_TOKEN }}
#           generateReleaseNotes: true
#           allowUpdates: true
#           skipIfReleaseExists: true

  build-common:
    runs-on: ${{ vars.LINUX_RUNNER }}
    name: Build & Test Common
    steps:
      - uses: actions/checkout@v3

  build-mobile:
    runs-on: ${{ vars.LINUX_RUNNER }}
    needs: build-common
    name: Build & Test Mobile
    steps:
      - uses: actions/checkout@v3

  build-tv:
    runs-on: ${{ vars.LINUX_RUNNER }}
    needs: build-common
    name: Build & Test TV
    steps:
      - uses: actions/checkout@v3

  build-mobile-android:
    runs-on: ${{ vars.LINUX_RUNNER }}
    name: Build Dev Mobile Android
    needs: [build-mobile, build-tv]
    steps:
      - uses: actions/checkout@v3

  build-mobile-ios:
    runs-on: ${{ vars.LINUX_RUNNER }}
    name: Build Dev Mobile iOS
    needs: [build-mobile, build-tv]
    steps:
      - uses: actions/checkout@v3
      
      - run: exit 1

  build-tv-android:
    runs-on: ${{ vars.LINUX_RUNNER }}
    name: Build Dev TV Android
    needs: [build-mobile, build-tv]
    if: vars.ENABLED_TV == 'true'
    steps:
      - uses: actions/checkout@v3

  build-tv-ios:
    runs-on: ${{ vars.LINUX_RUNNER }}
    name: Build Dev TV iOS 
    needs: [build-mobile, build-tv]
    if: vars.ENABLED_TV == 'true'
    steps:
      - uses: actions/checkout@v3

  end-to-end-execution:
    name: End-to-end Execution
    needs: [build-mobile-android, build-mobile-ios]
    runs-on: ${{ vars.LINUX_RUNNER }}
    if: true
    strategy:
      matrix:
        platform-name: [android, ios]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - run: exit 1

  deploy-to-firebase:
    name: Deploy to Firebase
    needs: [end-to-end-execution, build-mobile-android, build-mobile-ios]
    runs-on: ${{ vars.LINUX_RUNNER }}
    if: always() && needs.build-mobile-android.result == 'success' && needs.build-mobile-ios.result == 'success'
    strategy:
      matrix:
        platform: [android, ios]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  build-mobile-android-release:
    runs-on: ${{ vars.LINUX_RUNNER }}
    name: Build Release Mobile Android
    needs: [deploy-to-firebase, end-to-end-execution]
    if: always() && false && (needs.deploy-to-firebase.result == 'success')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  build-mobile-ios-release:
    runs-on: ${{ vars.LINUX_RUNNER }}
    name: Build Release Mobile iOS
    needs: [deploy-to-firebase, end-to-end-execution]
    if: always() && false && (needs.deploy-to-firebase.result == 'success')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  build-tv-android-release:
    runs-on: ${{ vars.LINUX_RUNNER }}
    name: Build Release TV Android 
    needs: [deploy-to-firebase, end-to-end-execution]
    if: false
    steps:
      - uses: actions/checkout@v3

  build-tv-ios-release:
    runs-on: ${{ vars.LINUX_RUNNER }}
    name: Build Release TV iOS
    needs: [deploy-to-firebase, end-to-end-execution]
    if: false
    steps:
      - uses: actions/checkout@v3

  deploy-amazon-appstore:
    name: Deploy to Amazon AppStore
    runs-on: ${{ vars.LINUX_RUNNER }}
    needs: [build-mobile-android-release, build-mobile-ios-release]
    if: always() && needs.build-mobile-android-release.result == 'success' && needs.build-mobile-ios-release.result == 'success'
    environment:
      name: amazon-appstore
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  deploy-google-playstore:
    name: Deploy to Google PlayStore
    runs-on: ${{ vars.LINUX_RUNNER }}
    needs: [build-mobile-android-release, build-mobile-ios-release]
    if: always() && needs.build-mobile-android-release.result == 'success' && needs.build-mobile-ios-release.result == 'success'
    environment:
      name: google-playstore
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  deploy-testflight:
    name: Deploy to TestFlight
    runs-on: ${{ vars.LINUX_RUNNER }}
    needs: [build-mobile-android-release, build-mobile-ios-release]
    if: always() && needs.build-mobile-android-release.result == 'success' && needs.build-mobile-ios-release.result == 'success'
    environment:
      name: testflight
    steps:
      - uses: actions/checkout@v3

  slack:
    name: Slack Notification
    runs-on: ${{ vars.LINUX_RUNNER }}
    needs: [deploy-amazon-appstore, deploy-google-playstore, deploy-testflight]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v3
