name: Release Build Check

on:
  pull_request:
    types: [labeled]
    branches: 
      - 'main'

jobs:
  trigger-jobs:
    runs-on: ubuntu-22.04
    name: Dispatch Release Build Event
    if: github.event.pull_request.labels.*.name == 'ready-for-regression'
    steps:
      - uses: peter-evans/repository-dispatch@v3
        with:
          event-type: release-build-check

      - name: Create Context Json file
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT >> github.event.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./github.event.json
          name: pull-request-event
