on:
  pull_request:
    types: [labeled]

jobs:
  trigger-jobs:
    runs-on: ubuntu-22.04
    name: Trigger Jobs
    steps:
      - run: |
          echo "Event: ${{ toJson(github.event) }}"

      - uses: peter-evans/repository-dispatch@v3
        with:
          event-type: release-build-check