name: test

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore: 
      - ./github/workflows/ci-cd.yml
#   schedule:
#     - cron: "*/6 * * * *"

# env:
#   ENVRIONMENT: |
#     ${{ 
#       (1 == 1 && 'prod')
#       || ( 1 == 0 && 'stage')
#     }}

jobs:
  artifact_validation_a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - run: |
          mkdir -p report/mobile-desktop/
          touch reportmobile-desktop/some_a.xml
     
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: mobile-desktop
          path: report/mobile-desktop/

  artifact_validation_b:
    runs-on: ubuntu-latest
    needs: [artifact_validation_a]
    steps:
      - uses: actions/checkout@v2
        
      - run: |
          mkdir -p report/mobile-desktop/
          touch reportmobile-desktop/some_b.xml
     
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: mobile-desktop
          path: report/mobile-desktop/

  artifact_validation_c:
    runs-on: ubuntu-latest
    needs: [artifact_validation_a, artifact_validation_b]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: mobile-desktop
          
      - run: ls -la
        
  shell_validation:
    runs-on: ubuntu-latest
    if: 1 == 2
    steps:
      - uses: actions/checkout@v2
        
      - run: |
          mkdir -p report/aje-mobile-report
          mkdir -p report/aja-mobile-report
          mkdir -p report/ajm-mobile-report
          mkdir -p report/ajb-mobile-report
          mkdir -p report/ajc-mobile-report
        
      - run: |
          touch report/aje-mobile-report/something.xml
          touch report/aja-mobile-report/something.xml
          touch report/ajm-mobile-report/something.xml
          touch report/ajb-mobile-report/something.xml
          touch report/ajc-mobile-report/something.xml
      
      - name: Check Artifacts Files
        id: check-artifacts-files
        run: echo "::set-output name=has_files::$(if [ -n "$(ls -A report/ 2>/dev/null)" ]; then echo true; else echo false; fi)"
        
      - run: echo "Okay, there is a file at least!"
        if: steps.check-artifacts-files.outputs.has_files == 'true'
         
  github-context:
    runs-on: ubuntu-latest
    if: 1 == 2
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" > github_context.json

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: github_context.json

