name: continuous integration

on:
  workflow_dispatch:
  push:
    branches: main
#   schedule:
#     - cron: "*/6 * * * *"

# env:
#   ENVRIONMENT: |
#     ${{ 
#       (1 == 1 && 'prod')
#       || ( 1 == 0 && 'stage')
#     }}

jobs:
  shell_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - run: |
          mkdir -p report/aje-mobile-report
          mkdir -p report/aja-mobile-report
          mkdir -p report/ajm-mobile-report
          mkdir -p report/ajb-mobile-report
          mkdir -p report/ajc-mobile-report
        
      - run: |
          touch report/aje-mobile-report/something.xml
          touch report/aja-mobile-report/something.xml
          touch report/ajm-mobile-report/something.xml
          touch report/ajb-mobile-report/something.xml
          touch report/ajc-mobile-report/something.xml
      
      - name: Check Artifacts Files
        id: check-artifacts-files
        run: echo "::set-output name=has_files::$(if [ -n "$(ls -A report/ 2>/dev/null)" ]; then echo true; else echo false; fi)"
        
      - run: echo "Okay, there is a file at least!"
        if: steps.check-artifacts-files.outputs.has_files == 'true'
         
  github-context:
    needs: [shell_validation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" > github_context.json

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: github_context.json

