name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - ./github/workflows/ci-cd.yml
      - ./github/workflows/bump-version.yml
  pull_request:
    branches:
      - mai*

env:
  RELEASE_NOTES: "Built from Branch: ${{ (github.event_name == 'push' && github.ref) || (github.event_name == 'pull_request' && github.head_ref) }}. CI Build URL: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
  BRANCH_NAME: ${{ (github.event_name == 'push' && github.event.repository.default_branch ) || (github.event_name == 'pull_request' && github.head_ref) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "build"
      
      - name: Audit
        id: exit-error
        run: exit 1
        
      - run: echo "::notice::Audit result was error"
        if: always() && (steps.exit-error.outcome == 'failure' || steps.exit-error.outcome == 'success')
        
      - run: echo "::warning::Unit Test"
        

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    env:
      ENVIRONMENT: qa
      SERVICE: cms
      VARS_FILE: vars.sh
    steps:
      - run: |
          echo "unit-tests"

  static-analysis:
    runs-on: ubuntu-latest
    needs: unit-tests
    if: always() && (needs.unit-tests.result == 'success' || needs.unit-tests.result == 'failure')
    steps:
      - run: echo "static-analysis"

  e2e-mobile:
    runs-on: ubuntu-latest
    needs: [build, unit-tests, static-analysis]
    if: contains(github.ref, 'main')
    steps:
      - run: echo "build"

  deploy:
    runs-on: ubuntu-latest
    needs: e2e-mobile
    if: github.event_name == 'push' && contains(github.ref, 'main')
    steps:
      - uses: ncipollo/release-action@v1
        env:
          TAG: ${{ secrets.APP_VERSION }}
        with:
          tag: v${{ env.TAG }}
          omitBody: true
          token: ${{ secrets.ACCESS_TOKEN }}
