name: test

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore: 
      - ./github/workflows/ci-cd.yml
  schedule:
    - cron: "6 * * * *"
  pull_request:
    branches: main
    
env:
  ENVIORNMENT: |
    ${{
       ((github.event.inputs.environment == 'prod') || (github.event_name == 'push' && github.ref == 'refs/heads/master') || (github.event_name == 'schedule')) && 'prod'
       || ((github.event.inputs.environment == 'stage') || (github.event_name == 'push' && github.ref == 'refs/heads/develop') || (github.event_name == 'schedule')) && 'stage'
    }}
    
jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: echo $ENVIORNMENT

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" > "context.json"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: context.json

