name: test

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore: 
      - ./github/workflows/ci-cd.yml
jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  check-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site: ${{ fromJson(["aje", "aja", "ajm"]) }}
    steps:
      - uses: actions/checkout@v2
      
      - run: echo "::warining::Site name is ${{ matrix.site }}"
    
  github-context:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" > github_context.json

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: github_context.json

