name: test

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore: 
      - ./github/workflows/ci-cd.yml
  pull_request:
    branches: main

env:
  CODE_PUSH_DEPLOYMENT: ${{ ( github.event_name == 'push' && github.event_name != 'one' && github.refs == 'two' && 'true' || 'false ) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        run: echo "build"
  
  saucelabs-deploy:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      file_id: ${{ steps.deploy.outputs.file_id }}
    steps:
      - id: deploy
        run: echo "::set-output name=file_id::abcd1234"
  
  codepush-deploy:
    runs-on: ubuntu-latest
    needs: build
    if: "false"
    outputs:
      file_id: ${{ steps.deploy.outputs.file_id }}
    steps:
      - id: deploy
        run: echo "::set-output name=file_id::wxyz5678"

  end-to-end:
    runs-on: ubuntu-latest
    needs: [saucelabs-deploy, codepush-deploy]
    if: always() && (needs.saucelabs-deploy.result == 'success' || needs.codepush-deploy.result == 'success')
    steps:
      - env:
          APP_ID: ${{ ((needs.saucelabs-deploy.result == 'success') && needs.saucelabs-deploy.outputs.file_id) || ((needs.codepush-deploy.result == 'success') && needs.codepush-deploy.outputs.file_id)}}
        run: echo "${{ env.APP_ID }}"
      
