name: test

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore: 
      - ./github/workflows/ci-cd.yml
  pull_request:
    branches: main

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})" >> $GITHUB_ENV
      
      - run: echo $CHANGED_FILES
    
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" > "context.json"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: context.json
