name: test

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore: 
      - ./github/workflows/ci-cd.yml
  pull_request:
    branches: main

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.git-diff.outputs.changed-files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: git-diff
        run: echo "::set-output name=changed-files::$(git diff --name-only ${{ github.event.before }}..${{ github.event.after }})"
      
      - run: echo $CHANGED_FILES
    
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT" > "context.json"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          path: context.json
          
  after-context:
    runs-on: ubuntu-latest
    needs: context
    if: "!contains(needs.context.outputs.changed-files, 'workflows/tests.yml')"
    steps:
      - run: echo ${{ needs.context.outputs.changed-files }} 
