on:
  repository_dispatch:
    types: [start-end-to-end-workflow]

jobs:
  end-to-end-execution:
    runs-on: ubuntu-latest
    name: ${{ github.event.client_payload.device-capabilities.platform-name }} execution
    steps:
      - name: Run Functional Tests
        env:
          APP_FILE_ID: ${{ github.event.client_payload.sauce-labs-options.file-id }}
          SAUCE_USERNAME: ${{ github.event.client_payload.sauce-labs-options.username }}
          SAUCE_ACCESS_KEY: ${{ github.event.client_payload.sauce-labs-options.access-key }}
          APPIUM_VERSION: ${{ github.event.client_payload.sauce-labs-options.access-key }}
          PLATFORM_NAME: ${{ github.event.client_payload.device-capabilities.platform-name }}
          PLATFORM_VERSION: ${{ github.event.client_payload.device-capabilities.platform-version }}
          DEVICE_NAME: ${{ github.event.client_payload.device-capabilities.device-name }}
          PHONEONLY: ${{ github.event.client_payload.device-capabilities.phoneonly }}
          BRANCH_NAME: ${{ github.event.client_payload.branch-name }}
        run: exit 1
        id: remote-e2e

      - uses: Sibz/github-status-action@v1
        if: always()
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "End-to-end ${{ github.event.client_payload.device-capabilities.platform-name }} execution"
          description: ${{ steps.remote-e2e.outcome == 'success' && 'Success' || 'Failed' }}
          state: ${{ steps.remote-e2e.outcome }}
          sha: ${{github.event.pull_request.head.sha || github.sha}}
