on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT >> github.event.json

      - uses: actions/upload-artifact@v4
        with:
          path: ./github.event.json
          name: pull-request-event
