on:
  workflow_run:
    workflows: [workflow-trigger]
    types:
      - completed

jobs:
  job-b:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder job with no dependencies
        run: echo toJson(${{ github.event }}) >> $GITHUB_ENV

  job-c:
    runs-on: ubuntu-latest
    needs: job-a
    steps:
      - name: Display input value
        run: |
          echo "Input Value: ${{ needs.job-a.outputs.device-name }}"
