on:
  workflow_call:
    inputs:
      file-name:
        required: true
        type: string

jobs:
  upload-context:
    runs-on: ubuntu-latest
    steps:
      - name: Create Context JSON file
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT >> github.json

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./github.json
          name: ${{ inputs.file-name }}
